### ISSUE TITLE
载入时发生错误

### ISSUE THREAD

**Issue by GreenChennai** [ssttkkl/MiraiBangumiPlugin#1]
mirai版本
1.0m4

2020-10-18 14:50:07 E/MiraiBangumiPlugin: java.lang.NoSuchMethodError: net.mamoe.mirai.console.data.AutoSavePluginConfig.<init>(Ljava/lang/String;)V
java.lang.NoSuchMethodError: net.mamoe.mirai.console.data.AutoSavePluginConfig.<init>(Ljava/lang/String;)V
        at com.ssttkkl.mirai.bangumiplugin.GeneralConfig.<init>(GeneralConfig.kt:7)
        at com.ssttkkl.mirai.bangumiplugin.GeneralConfig.<clinit>(GeneralConfig.kt:7)
        at com.ssttkkl.mirai.bangumiplugin.MiraiBangumiPlugin.onEnable(MiraiBangumiPlugin.kt:94)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:113)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:100)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:36)
        at net.mamoe.mirai.console.plugin.PluginManager.enable(PluginManager.kt:129)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:168)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:192)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:184)
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.startAsDaemon(MiraiConsolePureLoader.kt:150)
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.startAsDaemon$default(MiraiConsolePureLoader.kt:149)
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.main(MiraiConsolePureLoader.kt:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at pw.konge.mirai.console.wrapper.Wrapper.main(Wrapper.java:80)

**Comment by ssttkkl** [comment]
开发用的console版本是1.0-dev28，用到了不兼容1.0-M4的一些东西导致的报错。问就是正式版什么时候发布
